version: "3.1"

services:
  #app:
  #  build:
  #    context: .
  #  ports:
  #    - "3010:3000"
  #  env_file:
  #    - .env
  #  depends_on:
  #    - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db_data:/data/db

volumes:
  db_data:
    driver: local
